# Generated by Django 2.2.16 on 2020-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCar', '0002_misionyvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='car')),
                ('texto', models.TextField()),
            ],
        ),
    ]
