# Generated by Django 2.2.16 on 2020-10-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCar', '0003_galeria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galeria',
            new_name='Galeria1',
        ),
    ]
